import java.awt.*;
import java.awt.event.*;

class MyFrame8 extends Frame {

    //Label l1,l2,l3,l4;
    public MyFrame8() {
        super("Key Event Demo");

        setSize(400, 400);
        setLayout(null);

        addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent e) {
                System.out.println("Key Pressed: " + e.getKeyChar());
            }

            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {
                System.out.println("Key Released: " + e.getKeyChar());
            }

            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                System.out.println("Key Typed: " + e.getKeyChar());
            }
        });

        setVisible(true);
    }

    
}

public class KeyEvent {
    public static void main(String[] args) {
        MyFrame8 f = new MyFrame8();
        f.setSize(400, 400);    
        f.setVisible(true);
    }
}


//Notes:
// There are 3 event generated by keyboard
// 1. KeyPressed Event: When a key is pressed down
// 2. KeyReleased Event: When a key is released
// 3. KeyTyped Event: When a key is typed (pressed and released)
// To handle keyboard events in Java AWT, you can implement the KeyListener interface
// and override its methods: keyPressed(), keyReleased(), and keyTyped().

// In this example, we create a Frame that listens for keyboard events and prints
// the key character to the console when a key is pressed, released, or typed.
// Note: To ensure that the Frame receives keyboard events, it must be focused.
// You can click on the Frame to give it focus before typing.
// You can also use KeyAdapter class to avoid implementing all methods of KeyListener interface.
// KeyAdapter is an abstract class that implements KeyListener with empty methods.
// In this example, we extend KeyAdapter and override only the methods we need.
// This makes the code cleaner and easier to read.
